### ISSUE TITLE
Silverline Member Portal Registration

### ISSUE THREAD

**Issue by rendykstan** [newtoncircus/silverline-visualization-dashboard#21]
This is to support Starhub trials where older adults do not have a smartphone.

![20141228_155133](https://cloud.githubusercontent.com/assets/770642/5563410/0daf94ca-8eab-11e4-997b-48269666993d.jpg)

Where should the data be saved to in Parse?

Name: name of Senior class
Age: ageRange of User class, ageByYear of Senior class
Gender: gender of User class, gender of Senior class
Mobile Number: username of User class, phoneNumber of Senior class
Date of Birth: dateOfBirth of Senior class
Address: address of Senior class
Token: activationCode of PendingProfileActivation class
Password: userPassword of User class
Confirm Password: userPassword of User class
Register Hub: hubId, userId of SeniorHub class

This have been approved by Daryl.

**Comment by swarit7** [comment]
Implemented.
