### ISSUE TITLE
Companion Pairing without smart phone

### ISSUE THREAD

**Issue by rendykstan** [newtoncircus/silverline-visualization-dashboard#22]
This is to support Starhub trials where older adults do not have a smartphone and assuming that companions has smartphone and installed the companion app.

![20141228_162341](https://cloud.githubusercontent.com/assets/770642/5563443/0ca09108-8eae-11e4-96f7-d2579ba62434.jpg)

Page 1 - Login to Facebook

Page 2 - Enter older adult number and generate token using the number to verify and pair.

Mobile Number: username of User class
Token: activationCode of PendingProfileActivation class

Write to SeniorUsers in Parse after saving.

**Comment by swarit7** [comment]
Implemented.
